# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build electron

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  APP_NAME: helm-cli-helper

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run package
        uses: borales/actions-yarn@v4
        with:
          cmd: run package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.APP_NAME }}-${{ runner.os }}
          path: out
          overwrite: true
      - name: Compress binary (Windows)
        if: runner.os == 'Windows'
        run: |
          Compress-Archive -Path out\* -DestinationPath ${{ env.APP_NAME }}-windows.zip
      - name: Compress binary (Linux)
        if: runner.os == 'Linux'
        run: |
          cd out && zip -r ../${{ env.APP_NAME }}-linux.zip *
      - name: Compress binary (macOS)
        if: runner.os == 'macOS'
        run: |
          cd out && zip -r ../${{ env.APP_NAME }}-mac.zip *
      - name: Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: ${{ env.APP_NAME }}-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
